name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-code-formatting:
    if: github.event.pull_request.draft == false
    runs-on: [self-hosted, Linux, X64]
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0
    
    steps:
      - name: Remove git lfs hooks
        run: rm -rf ./.git/hooks

      - name: Check out code
        uses: actions/checkout@v4

      - name: Creating project
        run: cd JamGame/Assets/Scripts && dotnet new classlib --name JamGame --output . && rm Class1.cs

      - name: Move .editorconfig and .csharpierrc
        run: cd JamGame && mv .editorconfig Assets/Scripts && mv .csharpierrc.json Assets/Scripts

      - name: Check content
        run: ls -a -l JamGame/Assets/Scripts

      - name: Restore tools
        run:  cd JamGame/Assets/Scripts && dotnet tool restore --tool-manifest ../../.config/dotnet-tools.json
      
      - name: Check dotnet format version
        run: dotnet format --version

      - name: Run dotnet format
        run: dotnet format JamGame/Assets/Scripts/JamGame.csproj --verify-no-changes --no-restore -v d
      
      - name: Run csharpier format
        run: cd JamGame/Assets/Scripts && dotnet tool run dotnet-csharpier --config-path ".csharpierrc.json" . --check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/main' && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
