name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-format-dotnet:
    runs-on: self-hosted
    
    - name: Check out code
        uses: actions/checkout@v3

      - name: Run dotnet format
        run: dotnet format whitespace "./JamGame/Assets/Scripts/" --folder --verbosity diagnostic --verify-no-changes

  check-format-cscharpier:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run csharpier format
        run: dotnet csharpier '.\JamGame\Assets\Scripts\' --check
  
