name: dotnet format

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-format-dotnet:
    runs-on: self-hosted
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Creating sln
        run: dotnet new sln --name JamGame --output ./JamGame

      - name: Run dotnet format
        run: dotnet format JamGame/JamGame.sln --verbosity diagnostic --verify-no-changes --no-restore

  check-format-cscharpier:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run csharpier format
        run: dotnet csharpier '.\JamGame\Assets\Scripts\' --check
  
